wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: Deep Cnn
dataset:
  desc: null
  value: ImageNet - 256
epochs:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723668950
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 16
      - 23
      4: 3.12.4
      5: 0.17.6
      8:
      - 5
      13: linux-x86_64
