_wandb:
    value:
        cli_version: 0.18.3
        m:
            - "1": training.height
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": training._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": t_denoiser
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": max x
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": min x
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": min eps
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": training.count
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": training.filenames
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": training.captions
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": max eps
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": training.width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": training.format
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 9
                - 11
                - 12
                - 41
                - 49
                - 51
                - 55
                - 63
                - 71
                - 79
                - 103
            "2":
                - 1
                - 9
                - 11
                - 12
                - 41
                - 49
                - 51
                - 55
                - 63
                - 71
                - 79
                - 103
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.12.4
            "5": 0.18.3
            "6": 4.37.2
            "8":
                - 2
                - 5
            "12": 0.18.3
            "13": linux-x86_64
