name: dmog_env39
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.7.4=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.8.5=py312hca68cad_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - impi_rt=2021.13.0=ha770c72_720
  - importlib-metadata=8.2.0=pyha770c72_0
  - importlib_metadata=8.2.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.26.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h7900ff3_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - libedit=3.1.20191231=he28a2e2_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=14.1.0=h77fa898_0
  - libgomp=14.1.0=h77fa898_0
  - libnsl=2.0.1=hd590300_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mpi=1.0=impi
  - mpi4py=4.0.0=py312h80e6c4e_1
  - ncurses=6.5=h59595ed_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.3.1=h4bc722e_2
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py312h9a8786e_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.12.4=h194c7f8_0_cpython
  - python_abi=3.12=4_cp312
  - pyzmq=26.1.0=py312h7ab5c7e_0
  - readline=8.2=h8228510_1
  - setuptools=71.0.4=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.1=py312h9a8786e_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.5=h75354e8_4
  - zipp=3.19.2=pyhd8ed1ab_0
  - pip:
      - accelerate==0.33.0
      - blobfile==2.1.1
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - filelock==3.13.1
      - fonttools==4.53.1
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.24.5
      - idna==3.7
      - jinja2==3.1.3
      - kiwisolver==1.4.5
      - kornia==0.7.3
      - kornia-rs==0.1.5
      - lightning-utilities==0.11.6
      - lxml==4.9.4
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - opencv-python==4.10.0.84
      - pandas==2.2.2
      - pillow==10.2.0
      - protobuf==5.27.3
      - pycryptodomex==3.20.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - safetensors==0.4.4
      - scipy==1.14.0
      - sentry-sdk==2.12.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sympy==1.12
      - torch==2.4.0+cu118
      - torchaudio==2.4.0+cu118
      - torchmetrics==1.4.1
      - torchvision==0.19.0+cu118
      - tqdm==4.66.4
      - triton==3.0.0
      - typing-extensions==4.9.0
      - tzdata==2024.1
      - urllib3==2.2.2
      - wandb==0.17.6
prefix: /users/cmk2000/.conda/envs/dmog_env39
